name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend (Maven + JDK 21)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Make mvnw executable (Linux)
        working-directory: demo
        run: chmod +x ./mvnw

      - name: Build & Test (unit tests only)
        working-directory: demo
        run: ./mvnw -q -Dtest='!DemoApplicationTests' test

      - name: SonarCloud analyze
        working-directory: demo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw -q -DskipTests sonar:sonar \
            -Dsonar.organization=valentinaj24 \
            -Dsonar.projectKey=valentinaj24_to-do-app
